### ISSUE TITLE
Could not install

### ISSUE THREAD

**Issue by netesy** [coderius/yii2-hit-counter#1]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package coderius/yii2-hit-counter * is satisfiable by coderius/yii2-hit-counter[dev-master]
 but these conflict with your requirements or minimum-stability.

**Comment by coderius** [comment]
What is Your php version?

**Comment by netesy** [comment]
php 7.4.0 win32 vc15-x86

**Comment by netesy** [comment]
solved by using version 1.0.2.2

**Comment by coderius** [comment]
Ok. Thanks for ffeedback.
