### ISSUE TITLE
Fixed 'Js Processor Ram It must be an integer'

### ISSUE THREAD

**Issue by RubenOptima** [coderius/yii2-hit-counter#2]
If the browser does not detect the system ram, it does not store information in the database.
{"js_processor_ram":["Js Processor Ram It must be an integer."]}

I have fixed it in the 'detectJsVisitInfo' function as follows:
$data['js_processor_ram']   = ArrayHelper::getValue($array, 'ram') == 'undefined' ? 0 : ArrayHelper::getValue($array, 'ram');

**Comment by coderius** [comment]
Fixed 'Js Processor Ram It must be an integer
